In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('datasets/imdb_rating.csv')
df

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [3]:
new_show = [8.9 , 'GOT' , 'Crime' , 60]

In [8]:
df.loc[len(df)] = new_show

In [14]:
a = {'star_rating':7.8 , 'title':'NEW_SHOW' , 'genre':'Crime' , 'duration':67}

In [16]:
df.loc[10] = list(a.values())

[7.8, 'NEW_SHOW', 'Crime', 67]

In [18]:
df.append(a , ignore_index= True)

C:\Users\Mohammed Israr\AppData\Local\Temp\ipykernel_12576\888566535.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(a , ignore_index= True)

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139
10,8.9,GOT,Crime,60
11,8.9,GOT,Crime,60
12,8.9,GOT,Crime,60
13,7.8,NEW_SHOW,Crime,67

In [9]:
df

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139
10,8.9,GOT,Crime,60
13,8.9,GOT,Crime,60
12,8.9,GOT,Crime,60

# Drop

In [19]:
df

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139
10,8.9,GOT,Crime,60
13,8.9,GOT,Crime,60
12,8.9,GOT,Crime,60

In [ ]:
cleaned_data = df.drop([13 , 12 , 10 , 9] )

In [22]:
df.drop([13 , 12 , 10 , 9] , inplace = True)

In [25]:
df.drop(columns= 'genre')

   star_rating                                          title  duration
0          9.3                       The Shawshank Redemption       142
1          9.2                                  The Godfather       175
2          9.1                         The Godfather: Part II       200
3          9.0                                The Dark Knight       152
4          8.9                                   Pulp Fiction       154
5          8.9                                   12 Angry Men        96
6          8.9                 The Good, the Bad and the Ugly       161
7          8.9  The Lord of the Rings: The Return of the King       201
8          8.9                               Schindler's List       195

In [28]:
# 

df

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195

In [29]:
# Index
df.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [37]:
df.drop(df.tail().index)

   star_rating                     title   genre  duration
0          9.3  The Shawshank Redemption     XYZ       142
1          9.2             The Godfather   Crime       175
2          9.1    The Godfather: Part II   Crime       200
3          9.0           The Dark Knight  Action       152

# Replace

In [35]:
df.at[0 , 'genre'] = 'XYZ'

In [36]:
df

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,XYZ,142
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195

In [40]:
for i in df.index:
    if df.at[i , 'genre'] == 'Crime':
        df.at[i , 'genre'] = 'XYZ'

In [41]:
df

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,XYZ,142
1,9.2,The Godfather,XYZ,175
2,9.1,The Godfather: Part II,XYZ,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,XYZ,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195

In [42]:
df = pd.read_csv('datasets/weather_data_replace.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [44]:
df.replace([-99999 , '0'] , 100)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017          100          7  Sunny
2  1/3/2017           28        100   Snow
3  1/4/2017          100          7    100
4  1/5/2017           32        100   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5    100

In [45]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [46]:
df.replace({'temperature' : -99999 ,
           'windspeed':7  , 
           'event':'0'} , 100)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017          100        100  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017          100        100    100
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5    100

In [50]:
df.replace({'temperature' : -99999 ,
           'windspeed':7  , 
           'event':'0'} , {'temperature' :100 ,
           'windspeed':200  , 
           'event':300})

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017          100        200  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017          100        200    300
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5    300

In [51]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [53]:
df.replace({'temperature':-99999} , 100)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017          100          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017          100          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [54]:
df['temperature'].replace(-99999 , 100 , inplace = True)

In [55]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017          100          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017          100          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

# Sorting of a data frame

In [56]:
df = pd.read_csv('datasets/unsorted_imdb_rating.csv')
df

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.1,The Godfather,Crime,175
2,9.2,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.8,12 Angry Men,Drama,96
6,8.7,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.3,Schindler's List,Biography,195
9,8.1,Fight Club,Drama,139

In [57]:
df.sort_values(by = 'duration') #by =index , ascending =True

,star_rating,title,genre,duration
5,8.8,12 Angry Men,Drama,96
9,8.1,Fight Club,Drama,139
0,9.3,The Shawshank Redemption,Crime,142
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
6,8.7,"The Good, the Bad and the Ugly",Western,161
1,9.1,The Godfather,Crime,175
8,8.3,Schindler's List,Biography,195
2,9.2,The Godfather: Part II,Crime,200
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201

In [58]:
df.sort_values(by = 'duration' , ignore_index= True) #by =index , ascending =True

,star_rating,title,genre,duration
0,8.8,12 Angry Men,Drama,96
1,8.1,Fight Club,Drama,139
2,9.3,The Shawshank Redemption,Crime,142
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.7,"The Good, the Bad and the Ugly",Western,161
6,9.1,The Godfather,Crime,175
7,8.3,Schindler's List,Biography,195
8,9.2,The Godfather: Part II,Crime,200
9,8.9,The Lord of the Rings: The Return of the King,Adventure,201

In [62]:
df.sort_values(by = 'star_rating' , ascending= False)

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
2,9.2,The Godfather: Part II,Crime,200
1,9.1,The Godfather,Crime,175
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
5,8.8,12 Angry Men,Drama,96
6,8.7,"The Good, the Bad and the Ugly",Western,161
8,8.3,Schindler's List,Biography,195
9,8.1,Fight Club,Drama,139

In [68]:
df.sort_values(by = 'star_rating' )

,star_rating,title,genre,duration
9,8.1,Fight Club,Drama,139
8,8.3,Schindler's List,Biography,195
6,8.7,"The Good, the Bad and the Ugly",Western,161
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
3,9.0,The Dark Knight,Action,152
1,9.1,The Godfather,Crime,175
2,9.2,The Godfather: Part II,Crime,200
0,9.3,The Shawshank Redemption,Crime,142

In [69]:
df.sort_values(by = ['star_rating' , 'duration'] )

,star_rating,title,genre,duration
9,8.1,Fight Club,Drama,139
8,8.3,Schindler's List,Biography,195
6,8.7,"The Good, the Bad and the Ugly",Western,161
5,8.9,12 Angry Men,Drama,96
4,8.9,Pulp Fiction,Crime,154
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
3,9.0,The Dark Knight,Action,152
1,9.1,The Godfather,Crime,175
2,9.2,The Godfather: Part II,Crime,200
0,9.3,The Shawshank Redemption,Crime,142

In [70]:
df.sort_values(by = ['star_rating' , 'duration'] , ascending= False)

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
2,9.2,The Godfather: Part II,Crime,200
1,9.1,The Godfather,Crime,175
3,9.0,The Dark Knight,Action,152
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.7,"The Good, the Bad and the Ugly",Western,161
8,8.3,Schindler's List,Biography,195
9,8.1,Fight Club,Drama,139

In [72]:
df.sort_values(by = ['star_rating' , 'duration'] , ascending= [True , False] , inplace = True)

In [64]:
df.sort_values(by = ['star_rating' , 'duration'] , ascending= [True , False])

,star_rating,title,genre,duration
9,8.1,Fight Club,Drama,139
8,8.3,Schindler's List,Biography,195
6,8.7,"The Good, the Bad and the Ugly",Western,161
5,8.8,12 Angry Men,Drama,96
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
4,8.9,Pulp Fiction,Crime,154
3,9.0,The Dark Knight,Action,152
1,9.1,The Godfather,Crime,175
2,9.2,The Godfather: Part II,Crime,200
0,9.3,The Shawshank Redemption,Crime,142

In [75]:
df

,star_rating,title,genre,duration
9,8.1,Fight Club,Drama,139
8,8.3,Schindler's List,Biography,195
6,8.7,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
3,9.0,The Dark Knight,Action,152
1,9.1,The Godfather,Crime,175
2,9.2,The Godfather: Part II,Crime,200
0,9.3,The Shawshank Redemption,Crime,142

In [74]:
df.reset_index() # drop = False

,index,star_rating,title,genre,duration
0,9,8.1,Fight Club,Drama,139
1,8,8.3,Schindler's List,Biography,195
2,6,8.7,"The Good, the Bad and the Ugly",Western,161
3,7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
4,4,8.9,Pulp Fiction,Crime,154
5,5,8.9,12 Angry Men,Drama,96
6,3,9.0,The Dark Knight,Action,152
7,1,9.1,The Godfather,Crime,175
8,2,9.2,The Godfather: Part II,Crime,200
9,0,9.3,The Shawshank Redemption,Crime,142

In [76]:
df.reset_index(drop = True) # drop = True

,star_rating,title,genre,duration
0,8.1,Fight Club,Drama,139
1,8.3,Schindler's List,Biography,195
2,8.7,"The Good, the Bad and the Ugly",Western,161
3,8.9,The Lord of the Rings: The Return of the King,Adventure,201
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,9.0,The Dark Knight,Action,152
7,9.1,The Godfather,Crime,175
8,9.2,The Godfather: Part II,Crime,200
9,9.3,The Shawshank Redemption,Crime,142

# Concatination

In [78]:
india_weather = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [77]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [81]:
pd.concat([india_weather , us_weather] , ignore_index= True)

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [83]:
pd.concat([india_weather , us_weather]  , keys= ['INDIA' , 'US'])

             city  temperature  humidity
INDIA 0    mumbai           32        80
      1     delhi           45        60
      2  banglore           30        78
US    0  new york           21        68
      1   chicago           14        65
      2   orlando           35        75

In [84]:
del us_weather['humidity']

In [85]:
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [86]:
us_weather

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

In [87]:
pd.concat([india_weather , us_weather] , ignore_index= True)

       city  temperature  humidity
0    mumbai           32      80.0
1     delhi           45      60.0
2  banglore           30      78.0
3  new york           21       NaN
4   chicago           14       NaN
5   orlando           35       NaN

# Merge

In [88]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
df1

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

In [89]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
df2

       city  humidity
0   chicago        65
1  new york        68
2   orlando        75

In [90]:
pd.concat([df1 , df2])

       city  temperature  humidity
0  new york         21.0       NaN
1   chicago         14.0       NaN
2   orlando         35.0       NaN
0   chicago          NaN      65.0
1  new york          NaN      68.0
2   orlando          NaN      75.0

In [92]:
pd.merge(df1 , df2 , on = 'city' ) # how='inner' , on=None

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [93]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35, 38],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [94]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "humidity": [65,68,71],
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [95]:
pd.merge(df1 , df2 , on = 'city' )

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

In [96]:
pd.merge(df1 , df2 , on = 'city' , how = 'left')

        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35       NaN
3  baltimore           38       NaN

In [97]:
pd.merge(df1 , df2 , on = 'city' , how = 'right')

        city  temperature  humidity
0    chicago         14.0        65
1   new york         21.0        68
2  san diego          NaN        71

In [98]:
pd.merge(df1 , df2 , on = 'city' , how = 'outer')

        city  temperature  humidity
0   new york         21.0      68.0
1    chicago         14.0      65.0
2    orlando         35.0       NaN
3  baltimore         38.0       NaN
4  san diego          NaN      71.0

In [99]:
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [100]:
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [101]:
df2.loc[3] = ['new york' , 100]

In [102]:
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [103]:
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71
3   new york       100

In [104]:
pd.merge(df1 , df2 , on = 'city' , how = 'inner')

       city  temperature  humidity
0  new york           21        68
1  new york           21       100
2   chicago           14        65

# Group by