# Hello everyone

- Download the datasets folder from the google drive
- Unzip the folder and move the folder to the place you are working

# Pandas

- Data representation
- Can store Hetrogeous data

# Two types of data structures

- Series --> 1D
- Dataframe --> 2D

# Series

In [ ]:
# Different ways to create a series data 

1. List , tuple
2. Arrays
3. Dic

# List

In [2]:
import pandas as pd

In [4]:
lst = ['India' , 'Nepal' , 'Bangladesh' , 'China' , 'Japan']

ser = pd.Series(lst)

print(ser , type(ser))

0         India
1         Nepal
2    Bangladesh
3         China
4         Japan
dtype: object <class 'pandas.core.series.Series'>

In [6]:
lst = ('India' , 'Nepal' , 'Bangladesh' , 'China' , 'Japan')

ser = pd.Series(lst)

print(ser)

0         India
1         Nepal
2    Bangladesh
3         China
4         Japan
dtype: object

In [7]:
lst = {'India' , 'Nepal' , 'Bangladesh' , 'China' , 'Japan'}

ser = pd.Series(lst)

print(ser)

TypeError: 'set' type is unordered

In [9]:
import numpy as np


arr = np.arange(12)**2

ser = pd.Series(arr)

print(ser)

0       0
1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
11    121
dtype: int32

In [10]:
lst = {'India':23 , 'Nepal':56 , 'Bangladesh':56 , 'China':76 , 'Japan':87}

ser = pd.Series(lst)

print(ser)

India         23
Nepal         56
Bangladesh    56
China         76
Japan         87
dtype: int64

In [11]:
lst = ['India' , 'Nepal' , 'Bangladesh' , 'China' , 'Japan']

ser = pd.Series(lst)

print(ser , type(ser))

0         India
1         Nepal
2    Bangladesh
3         China
4         Japan
dtype: object <class 'pandas.core.series.Series'>

In [12]:
lst = ['India' , 'Nepal' , 'Bangladesh' , 'China' , 'Japan']

ser = pd.Series(lst , index = ['a' , 'b' , 'c' , 'd' ,'e'])

print(ser , type(ser))

a         India
b         Nepal
c    Bangladesh
d         China
e         Japan
dtype: object <class 'pandas.core.series.Series'>

In [18]:
lst = {'India':23 , 'Nepal':'56' , 'Bangladesh':56 , 'China':76 , 'Japan':87}

ser = pd.Series(lst , index = ['a' , 'b' , 'India' , 'China'])

print(ser)

a        NaN
b        NaN
India     23
China     76
dtype: object

In [14]:
lst = ['India' , 'Nepal' , 'Bangladesh' , 'China' , 'Japan']

ser = pd.Series(lst , index = ['a' , 'b' , 'c' , 'd' ])

print(ser , type(ser))

ValueError: Length of values (5) does not match length of index (4)

In [16]:
lst = ['India' , 'Nepal' , 'Bangladesh' , 'China' , 'Japan']

ser = pd.Series(lst )

print(ser , type(ser))

0         India
1         Nepal
2    Bangladesh
3         China
4         Japan
dtype: object <class 'pandas.core.series.Series'>

In [17]:
type(np.nan)

float

In [19]:
lst = ['India' , 'Nepal' , 'Bangladesh' , 'China' , 'Japan']

ser = pd.Series(lst , index = ['a' , 'b' , 'c' , 'd' ,'e'])

print(ser , type(ser))

a         India
b         Nepal
c    Bangladesh
d         China
e         Japan
dtype: object <class 'pandas.core.series.Series'>

In [22]:
lst = {'India':23 , 'Nepal':'56' , 'Bangladesh':56 , 'China':76 , 'Japan':87}

ser = pd.Series(lst , index = ['India' , 'China' , 'America'])

print(ser)

India       23
China       76
America    NaN
dtype: object

In [34]:
lst = ['India' , 'Nepal' , 'Bangladesh' , 'China' , 'Japan']

ser = pd.Series(lst , index = ['a' , 'g' , 'c' , 'd' ,'e'])

print(ser , type(ser))

a         India
g         Nepal
c    Bangladesh
d         China
e         Japan
dtype: object <class 'pandas.core.series.Series'>

# Indexing and slicing

- Zero indexing
start --> inclusive
stop --> exclusive

- User defined indexing
start --> and stop ----> inclusive

In [25]:
ser

a         India
b         Nepal
c    Bangladesh
d         China
e         Japan
dtype: object

In [26]:
ser[2]

'Bangladesh'

In [27]:
ser[-2]

'China'

In [28]:
ser['c']

'Bangladesh'

In [30]:
ser[1:4]

b         Nepal
c    Bangladesh
d         China
dtype: object

In [32]:
ser['b':'e']

b         Nepal
c    Bangladesh
d         China
e         Japan
dtype: object

In [35]:
ser

a         India
g         Nepal
c    Bangladesh
d         China
e         Japan
dtype: object

In [40]:
ser['d':'g':-1]

d         China
c    Bangladesh
g         Nepal
dtype: object

In [42]:
brics_country = ['Brazil', 'Russia', 'India', 'China', 'South Africa']

brics_currency = ['Real', 'Ruble', 'Rupee', 'Renminbi', 'Rand' ]

s=pd.Series(brics_currency,index=brics_country)
s['Russia':'China']

Russia       Ruble
India        Rupee
China     Renminbi
dtype: object

In [ ]:
# Convert it into a ser data
# - Keep brics_currency as value
# - Keep brics_country as index

In [ ]:
# Extract the the currency of  'Russia', 'India', 'China --> Custom idexing

# Data frame

In [43]:
brics_country = ['Brazil', 'Russia', 'India', 'China', 'South Africa']

brics_currency = ['Real', 'Ruble', 'Rupee', 'Renminbi', 'Rand' ]

In [46]:
pd.Series(brics_currency)

0        Real
1       Ruble
2       Rupee
3    Renminbi
4        Rand
dtype: object

In [45]:
df = pd.DataFrame(brics_currency)
df

          0
0      Real
1     Ruble
2     Rupee
3  Renminbi
4      Rand

In [47]:
df = pd.DataFrame({'Col_1' : brics_country , 
                  'Col_2' : brics_currency})
df

          Col_1     Col_2
0        Brazil      Real
1        Russia     Ruble
2         India     Rupee
3         China  Renminbi
4  South Africa      Rand

In [48]:
brics_country = ['Brazil', 'Russia', 'India', 'China', 'South Africa']

brics_currency = ['Real', 'Ruble', 'Rupee', 'Renminbi', 'Rand' ]

In [49]:
df = pd.DataFrame({'Col_1' : brics_country , 
                  'Col_2' : brics_currency})
df

ValueError: All arrays must be of the same length

In [51]:
df = pd.DataFrame({'Col_1' : pd.Series(brics_country) , 
                  'Col_2' : pd.Series(brics_currency)})
df

          Col_1     Col_2
0        Brazil      Real
1        Russia     Ruble
2         India     Rupee
3         China  Renminbi
4  South Africa       NaN

In [60]:
brics_country = ['Brazil', 'Russia', 'India', 'China', 'South Africa']

brics_currency = ['Real', 'Ruble', 'Rupee',None,'Rand' ]

In [61]:
df = pd.DataFrame({'Col_1' : pd.Series(brics_country) , 
                  'Col_2' : pd.Series(brics_currency)})
df

          Col_1  Col_2
0        Brazil   Real
1        Russia  Ruble
2         India  Rupee
3         China   None
4  South Africa   Rand

In [73]:
df_dict = {'Year' : [1990, 1994, 1998, 2002 ],
           'Country' : ['Italy', 'USA', 'France', 'Japan'],
           'Winner' : ['Germany', 'Brazil', 'France', 'Brazil'],
           'GoalScored' : [115, 141, 171, 161]
          }


df = pd.DataFrame(df_dict)
df

   Year Country   Winner  GoalScored
0  1990   Italy  Germany         115
1  1994     USA   Brazil         141
2  1998  France   France         171
3  2002   Japan   Brazil         161

In [75]:
df_dict = {'Year' : [1990, 1994, 1998, 2002 ],
           'Country' : ['Italy', 'USA', 'France', 'Japan'],
           'Winner' : ['Germany', 'Brazil', 'France', 'Brazil'],
           'GoalScored' : [115,None, 171, 161]
          }


df = pd.DataFrame(df_dict)
df

   Year Country   Winner  GoalScored
0  1990   Italy  Germany       115.0
1  1994     USA   Brazil         NaN
2  1998  France   France       171.0
3  2002   Japan   Brazil       161.0

In [77]:
df_lotuples = [(2002, 'Japan', 'Brazil', 161), 
                (2006, 'Germany', 'Italy', 147), 
                (2010, 'South Africa', 'Spain', 145),
                (2014, 'Brazil', 'Germany', 171)
              ]


df = pd.DataFrame(df_lotuples)
df

      0             1        2    3
0  2002         Japan   Brazil  161
1  2006       Germany    Italy  147
2  2010  South Africa    Spain  145
3  2014        Brazil  Germany  171

In [78]:
df_lotuples = [(2002, 'Japan', 'Brazil', 161), 
                (2006, 'Germany', 'Italy', 147), 
                (2010, 'South Africa', 'Spain', 145),
                (2014, 'Brazil', 'Germany', 171)
              ]


df = pd.DataFrame(df_lotuples , columns= ['Year' , 'Country' , 'Winner' , 'Goal'])
df

   Year       Country   Winner  Goal
0  2002         Japan   Brazil   161
1  2006       Germany    Italy   147
2  2010  South Africa    Spain   145
3  2014        Brazil  Germany   171

In [79]:
df_lotuples = [(2002, 'Japan', 'Brazil', 161), 
                (2006, 'Germany', 'Italy', 147), 
                (2010, 'South Africa', 'Spain', 145),
                (2014, 'Brazil', 'Germany', 171)
              ]


df = pd.DataFrame(df_lotuples , columns= ['Year' , 'Country' , 'Winner' , 'Goal'] , index = ['a' , 'b' , 'c' , 'd'])
df

   Year       Country   Winner  Goal
a  2002         Japan   Brazil   161
b  2006       Germany    Italy   147
c  2010  South Africa    Spain   145
d  2014        Brazil  Germany   171

In [80]:
df_dict = {'Year' : [1990, 1994, 1998, 2002 ],
           'Country' : ['Italy', 'USA', 'France', 'Japan'],
           'Winner' : ['Germany', 'Brazil', 'France', 'Brazil'],
           'GoalScored' : [115,None, 171, 161]
          }


df = pd.DataFrame(df_dict)
df

   Year Country   Winner  GoalScored
0  1990   Italy  Germany       115.0
1  1994     USA   Brazil         NaN
2  1998  France   France       171.0
3  2002   Japan   Brazil       161.0

# Loading the data from an external source

In [89]:
# CSV

df = pd.read_csv('datasets/data.csv')
df

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Afghanistan,Southern Asia,153.0,3.575,0.319820,0.302850,0.303350,0.234140,0.097190,0.365100,1.952100,2015
1,Albania,Central and Eastern Europe,95.0,4.959,0.878670,0.804340,0.813250,0.357330,0.064130,0.142720,1.898940,2015
2,Algeria,Middle East and Northern Africa,68.0,5.605,0.939290,1.077720,0.617660,0.285790,0.173830,0.078220,2.432090,2015
3,Angola,Sub-Saharan Africa,137.0,4.033,0.757780,0.860400,0.166830,0.103840,0.071220,0.123440,1.949390,2015
4,Argentina,Latin America and Caribbean,30.0,6.574,1.053510,1.248230,0.787230,0.449740,0.084840,0.114510,2.836000,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
490,Venezuela,Latin America and Caribbean,82.0,5.250,1.128431,1.431338,0.617144,0.153997,0.064491,0.065020,1.789464,2017
491,Vietnam,Southeastern Asia,94.0,5.074,0.788548,1.277491,0.652169,0.571056,0.087633,0.234968,1.462319,2017
492,Yemen,Middle East and Northern Africa,146.0,3.593,0.591683,0.935382,0.310081,0.249464,0.056767,0.104125,1.345601,2017
493,Zambia,Sub-Saharan Africa,116.0,4.514,0.636407,1.003187,0.257836,0.461603,0.078214,0.249580,1.826705,2017
494,Zimbabwe,Sub-Saharan Africa,138.0,3.875,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143,1.597970,2017

In [90]:
# Excel

df = pd.read_excel('datasets/football_worldcup.xlsx')
df

   Year       Country    Winner   Runners-Up  GoalsScored  MatchesPlayed
0  1990         Italy  Germany     Argentina          115             52
1  1994           USA    Brazil        Italy          141             52
2  1998        France    France       Brazil          171             64
3  2002         Japan    Brazil      Germany          161             64
4  2006       Germany     Italy       France          147             64
5  2010  South Africa     Spain  Netherlands          145             64
6  2014        Brazil   Germany    Argentina          171             64

# Pandas basics

In [91]:
df = pd.read_csv('datasets/data.csv')
df

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Afghanistan,Southern Asia,153.0,3.575,0.319820,0.302850,0.303350,0.234140,0.097190,0.365100,1.952100,2015
1,Albania,Central and Eastern Europe,95.0,4.959,0.878670,0.804340,0.813250,0.357330,0.064130,0.142720,1.898940,2015
2,Algeria,Middle East and Northern Africa,68.0,5.605,0.939290,1.077720,0.617660,0.285790,0.173830,0.078220,2.432090,2015
3,Angola,Sub-Saharan Africa,137.0,4.033,0.757780,0.860400,0.166830,0.103840,0.071220,0.123440,1.949390,2015
4,Argentina,Latin America and Caribbean,30.0,6.574,1.053510,1.248230,0.787230,0.449740,0.084840,0.114510,2.836000,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
490,Venezuela,Latin America and Caribbean,82.0,5.250,1.128431,1.431338,0.617144,0.153997,0.064491,0.065020,1.789464,2017
491,Vietnam,Southeastern Asia,94.0,5.074,0.788548,1.277491,0.652169,0.571056,0.087633,0.234968,1.462319,2017
492,Yemen,Middle East and Northern Africa,146.0,3.593,0.591683,0.935382,0.310081,0.249464,0.056767,0.104125,1.345601,2017
493,Zambia,Sub-Saharan Africa,116.0,4.514,0.636407,1.003187,0.257836,0.461603,0.078214,0.249580,1.826705,2017
494,Zimbabwe,Sub-Saharan Africa,138.0,3.875,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143,1.597970,2017

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495 entries, 0 to 494
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        495 non-null    object
 1   Region                         495 non-null    object
 2   Happiness Rank                 470 non-null    float64
 3   Happiness Score                470 non-null    float64
 4   Economy (GDP per Capita)       470 non-null    float64
 5   Family                         470 non-null    float64
 6   Health (Life Expectancy)       470 non-null    float64
 7   Freedom                        470 non-null    float64
 8   Trust (Government Corruption)  470 non-null    float64
 9   Generosity                     470 non-null    float64
 10  Dystopia Residual              470 non-null    float64
 11  Year                           495 non-null    int64
dtypes: float64(9), int64(1), object(2)
memory usage: 46.5+ KB

In [96]:
df.head()

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Afghanistan,Southern Asia,153.0,3.575,0.31982,0.30285,0.30335,0.23414,0.09719,0.36510,1.95210,2015
1,Albania,Central and Eastern Europe,95.0,4.959,0.87867,0.80434,0.81325,0.35733,0.06413,0.14272,1.89894,2015
2,Algeria,Middle East and Northern Africa,68.0,5.605,0.93929,1.07772,0.61766,0.28579,0.17383,0.07822,2.43209,2015
3,Angola,Sub-Saharan Africa,137.0,4.033,0.75778,0.86040,0.16683,0.10384,0.07122,0.12344,1.94939,2015
4,Argentina,Latin America and Caribbean,30.0,6.574,1.05351,1.24823,0.78723,0.44974,0.08484,0.11451,2.83600,2015

In [98]:
df.head(1)

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Afghanistan,Southern Asia,153.0,3.575,0.31982,0.30285,0.30335,0.23414,0.09719,0.3651,1.9521,2015

In [102]:
df.tail(15)

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
480,Tunisia,Middle East and Northern Africa,102.0,4.805,1.007266,0.868351,0.613212,0.289681,0.086723,0.049693,1.890251,2017
481,Turkey,Middle East and Northern Africa,69.0,5.500,1.198274,1.337753,0.637606,0.300741,0.099672,0.046693,1.879278,2017
482,Turkmenistan,Central and Eastern Europe,59.0,5.822,1.130777,1.493149,0.437726,0.418272,0.259270,0.249925,1.832910,2017
483,Uganda,Sub-Saharan Africa,133.0,4.081,0.381431,1.129828,0.217633,0.443186,0.057070,0.325766,1.526363,2017
484,Ukraine,Central and Eastern Europe,132.0,4.096,0.894652,1.394538,0.575904,0.122975,0.023029,0.270061,0.814382,2017
485,United Arab Emirates,Middle East and Northern Africa,21.0,6.648,1.626343,1.266410,0.726798,0.608345,0.324490,0.360942,1.734704,2017
486,United Kingdom,Western Europe,19.0,6.714,1.441634,1.496460,0.805336,0.508190,0.265428,0.492774,1.704144,2017
487,United States,North America,14.0,6.993,1.546259,1.419921,0.774287,0.505741,0.135639,0.392579,2.218113,2017
488,Uruguay,Latin America and Caribbean,28.0,6.454,1.217560,1.412228,0.719217,0.579392,0.178062,0.175097,2.172410,2017
489,Uzbekistan,Central and Eastern Europe,47.0,5.971,0.786441,1.548969,0.498273,0.658249,0.246528,0.415984,1.816914,2017
490,Venezuela,Latin America and Caribbean,82.0,5.250,1.128431,1.431338,0.617144,0.153997,0.064491,0.065020,1.789464,2017
491,Vietnam,Southeastern Asia,94.0,5.074,0.788548,1.277491,0.652169,0.571056,0.087633,0.234968,1.462319,2017
492,Yemen,Middle East and Northern Africa,146.0,3.593,0.591683,0.935382,0.310081,0.249464,0.056767,0.104125,1.345601,2017
493,Zambia,Sub-Saharan Africa,116.0,4.514,0.636407,1.003187,0.257836,0.461603,0.078214,0.249580,1.826705,2017
494,Zimbabwe,Sub-Saharan Africa,138.0,3.875,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143,1.597970,2017

In [106]:
df.tail(495)

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Afghanistan,Southern Asia,153.0,3.575,0.319820,0.302850,0.303350,0.234140,0.097190,0.365100,1.952100,2015
1,Albania,Central and Eastern Europe,95.0,4.959,0.878670,0.804340,0.813250,0.357330,0.064130,0.142720,1.898940,2015
2,Algeria,Middle East and Northern Africa,68.0,5.605,0.939290,1.077720,0.617660,0.285790,0.173830,0.078220,2.432090,2015
3,Angola,Sub-Saharan Africa,137.0,4.033,0.757780,0.860400,0.166830,0.103840,0.071220,0.123440,1.949390,2015
4,Argentina,Latin America and Caribbean,30.0,6.574,1.053510,1.248230,0.787230,0.449740,0.084840,0.114510,2.836000,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
490,Venezuela,Latin America and Caribbean,82.0,5.250,1.128431,1.431338,0.617144,0.153997,0.064491,0.065020,1.789464,2017
491,Vietnam,Southeastern Asia,94.0,5.074,0.788548,1.277491,0.652169,0.571056,0.087633,0.234968,1.462319,2017
492,Yemen,Middle East and Northern Africa,146.0,3.593,0.591683,0.935382,0.310081,0.249464,0.056767,0.104125,1.345601,2017
493,Zambia,Sub-Saharan Africa,116.0,4.514,0.636407,1.003187,0.257836,0.461603,0.078214,0.249580,1.826705,2017
494,Zimbabwe,Sub-Saharan Africa,138.0,3.875,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143,1.597970,2017

In [105]:
df

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Afghanistan,Southern Asia,153.0,3.575,0.319820,0.302850,0.303350,0.234140,0.097190,0.365100,1.952100,2015
1,Albania,Central and Eastern Europe,95.0,4.959,0.878670,0.804340,0.813250,0.357330,0.064130,0.142720,1.898940,2015
2,Algeria,Middle East and Northern Africa,68.0,5.605,0.939290,1.077720,0.617660,0.285790,0.173830,0.078220,2.432090,2015
3,Angola,Sub-Saharan Africa,137.0,4.033,0.757780,0.860400,0.166830,0.103840,0.071220,0.123440,1.949390,2015
4,Argentina,Latin America and Caribbean,30.0,6.574,1.053510,1.248230,0.787230,0.449740,0.084840,0.114510,2.836000,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
490,Venezuela,Latin America and Caribbean,82.0,5.250,1.128431,1.431338,0.617144,0.153997,0.064491,0.065020,1.789464,2017
491,Vietnam,Southeastern Asia,94.0,5.074,0.788548,1.277491,0.652169,0.571056,0.087633,0.234968,1.462319,2017
492,Yemen,Middle East and Northern Africa,146.0,3.593,0.591683,0.935382,0.310081,0.249464,0.056767,0.104125,1.345601,2017
493,Zambia,Sub-Saharan Africa,116.0,4.514,0.636407,1.003187,0.257836,0.461603,0.078214,0.249580,1.826705,2017
494,Zimbabwe,Sub-Saharan Africa,138.0,3.875,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143,1.597970,2017

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495 entries, 0 to 494
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        495 non-null    object
 1   Region                         495 non-null    object
 2   Happiness Rank                 470 non-null    float64
 3   Happiness Score                470 non-null    float64
 4   Economy (GDP per Capita)       470 non-null    float64
 5   Family                         470 non-null    float64
 6   Health (Life Expectancy)       470 non-null    float64
 7   Freedom                        470 non-null    float64
 8   Trust (Government Corruption)  470 non-null    float64
 9   Generosity                     470 non-null    float64
 10  Dystopia Residual              470 non-null    float64
 11  Year                           495 non-null    int64
dtypes: float64(9), int64(1), object(2)
memory usage: 46.5+ KB

In [115]:
pd.set_option('display.max_rows' , 10)

In [113]:
df

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Afghanistan,Southern Asia,153.0,3.575,0.319820,0.302850,0.303350,0.234140,0.097190,0.365100,1.952100,2015
1,Albania,Central and Eastern Europe,95.0,4.959,0.878670,0.804340,0.813250,0.357330,0.064130,0.142720,1.898940,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
493,Zambia,Sub-Saharan Africa,116.0,4.514,0.636407,1.003187,0.257836,0.461603,0.078214,0.249580,1.826705,2017
494,Zimbabwe,Sub-Saharan Africa,138.0,3.875,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143,1.597970,2017

In [116]:
df.describe()

,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
count,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,495.000000
mean,78.829787,5.370728,0.927830,0.990347,0.579968,0.402828,0.134790,0.242241,2.092717,2016.000000
std,45.281408,1.136998,0.415584,0.318707,0.240161,0.150356,0.111313,0.131543,0.565772,0.817323
min,1.000000,2.693000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580,2015.000000
25%,40.000000,4.509000,0.605292,0.793000,0.402301,0.297615,0.059777,0.152831,1.737975,2015.000000
50%,79.000000,5.282500,0.995439,1.025665,0.630053,0.418347,0.099502,0.223140,2.094640,2016.000000
75%,118.000000,6.233750,1.252443,1.228745,0.768298,0.516850,0.173161,0.315824,2.455575,2017.000000
max,158.000000,7.587000,1.870766,1.610574,1.025250,0.669730,0.551910,0.838075,3.837720,2017.000000

In [118]:
df.describe(include = 'object')

            Country              Region
count           495                 495
unique          165                  10
top     Afghanistan  Sub-Saharan Africa
freq              3                 129

# Indexing and slicing

In [121]:
# Selcting 1 columns

df['Region']

0                        Southern Asia
1           Central and Eastern Europe
2      Middle East and Northern Africa
3                   Sub-Saharan Africa
4          Latin America and Caribbean
                    ...
490        Latin America and Caribbean
491                  Southeastern Asia
492    Middle East and Northern Africa
493                 Sub-Saharan Africa
494                 Sub-Saharan Africa
Name: Region, Length: 495, dtype: object

In [123]:
# Selcting multiple columns

df[['Region' , 'Country' , 'Freedom']]

                              Region      Country   Freedom
0                      Southern Asia  Afghanistan  0.234140
1         Central and Eastern Europe      Albania  0.357330
2    Middle East and Northern Africa      Algeria  0.285790
3                 Sub-Saharan Africa       Angola  0.103840
4        Latin America and Caribbean    Argentina  0.449740
..                               ...          ...       ...
490      Latin America and Caribbean    Venezuela  0.153997
491                Southeastern Asia      Vietnam  0.571056
492  Middle East and Northern Africa        Yemen  0.249464
493               Sub-Saharan Africa       Zambia  0.461603
494               Sub-Saharan Africa     Zimbabwe  0.336384

[495 rows x 3 columns]

In [124]:
df['Region'][491]

'Southeastern Asia'

In [126]:
df.at[491 , 'Country'] # row , columne

'Vietnam'

In [128]:
df['Happiness Rank'][1] = 100

C:\Users\Mohammed Israr\AppData\Local\Temp\ipykernel_6308\822338944.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Happiness Rank'][1] = 100

In [130]:
df.at[1 , 'Happiness Rank'] = 200

# Slicing