In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('datasets/citibike_tripdata.csv')
df

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32423,396,2018-05-30 13:49:18,2018-05-30 13:55:55,3184,Paulus Hook,3279,Dixon Mills,29639,Join Citi Bike for $14.95/month,Subscriber
32424,313,2018-05-30 13:49:21,2018-05-30 13:54:35,3202,Newport PATH,3639,Harborside,26301,$25 Off Annual Membership,Subscriber
32425,316,2018-05-30 13:49:51,2018-05-30 13:55:08,3220,5 Corners Library,3195,Sip Ave,29260,Annual Membership,Subscriber
32426,1130,2018-05-30 13:50:52,2018-05-30 14:09:42,3281,Leonard Gordon Park,3213,Van Vorst Park,26239,Annual Membership,Subscriber
32427,369,2018-05-30 13:50:58,2018-05-30 13:57:08,3220,5 Corners Library,3207,Oakland Ave,33660,Annual Membership,Subscriber

In [4]:
df.at[3 , 'tripduration'] = 200

In [7]:
# Extract top 10 bike id


df['bikeid'].head(10)

0    33558
1    33593
2    29217
3    29662
4    15271
5    29298
6    33619
7    33624
8    26300
9    33555
Name: bikeid, dtype: int64

# Slicing

- Normal slicing
     a) Zero slicing
     b) User defined slicing
     c) cannot perform slicing on columns
     
     
- Loc
    a) Can perform slicing on rows and columns
    b) Only userdefined indexing is allowed
    c) Start and stop inclusive
    d) dataframe.loc['Row_start_name' : 'Row_stop_name' : step_for_rows , 'Columns_name' : 'Columns_Stop_name': step]

- iloc
    a) Can perform slicing on rows and columns
    b) Only Zero indexing indexing is allowed
    c) Start is inclusive and stop is exclusive
    d) dataframe.iloc['Row_start_index' : 'Row_stop_index' : step_for_rows , 'Columns_index' : 'Columns_index': step]

- Normal slicing
You cannot perform slicing on columns, Only on rows it is possible

     a) Zero slicing
     b) User defined slicing

In [10]:
df[1:5]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,200,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber

In [12]:
df[5:101:5]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
10,353,2018-05-01 05:18:36,2018-05-01 05:24:29,3225,Baldwin at Montgomery,3195,Sip Ave,33627,Annual Membership,Subscriber
15,178,2018-05-01 05:34:30,2018-05-01 05:37:28,3267,Morris Canal,3183,Exchange Place,26190,Annual Membership,Subscriber
20,261,2018-05-01 05:56:06,2018-05-01 06:00:28,3270,Jersey & 6th St,3202,Newport PATH,29540,Annual Membership,Subscriber
25,77,2018-05-01 06:06:27,2018-05-01 06:07:45,3184,Paulus Hook,3183,Exchange Place,29290,Annual Membership,Subscriber
30,452,2018-05-01 06:15:55,2018-05-01 06:23:28,3280,Astor Place,3195,Sip Ave,33658,Annual Membership,Subscriber
35,367,2018-05-01 06:28:03,2018-05-01 06:34:10,3278,Monmouth and 6th,3186,Grove St PATH,26235,Single Ride,Customer
40,157,2018-05-01 06:35:08,2018-05-01 06:37:45,3186,Grove St PATH,3481,York St,26160,Annual Membership,Subscriber
45,136,2018-05-01 06:37:05,2018-05-01 06:39:22,3214,Essex Light Rail,3183,Exchange Place,26179,Annual Membership from Citi Bike App,Subscriber
50,362,2018-05-01 06:42:19,2018-05-01 06:48:22,3184,Paulus Hook,3202,Newport PATH,26163,Annual Membership,Subscriber
55,239,2018-05-01 06:49:01,2018-05-01 06:53:01,3267,Morris Canal,3183,Exchange Place,33595,Annual Membership from Citi Bike App,Subscriber
60,353,2018-05-01 06:51:13,2018-05-01 06:57:06,3203,Hamilton Park,3186,Grove St PATH,29434,Annual Membership,Subscriber
65,555,2018-05-01 06:56:20,2018-05-01 07:05:35,3198,Heights Elevator,3206,Hilltop,33560,Annual Membership from Citi Bike App,Subscriber
70,144,2018-05-01 06:59:47,2018-05-01 07:02:11,3481,York St,3186,Grove St PATH,26269,Annual Membership,Subscriber
75,92,2018-05-01 07:02:07,2018-05-01 07:03:39,3199,Newport Pkwy,3202,Newport PATH,29577,Annual Membership,Subscriber
80,254,2018-05-01 07:06:47,2018-05-01 07:11:01,3269,Brunswick & 6th,3279,Dixon Mills,29513,Annual Membership,Subscriber
85,223,2018-05-01 07:10:45,2018-05-01 07:14:29,3203,Hamilton Park,3186,Grove St PATH,33635,Annual Membership,Subscriber
90,855,2018-05-01 07:14:14,2018-05-01 07:28:29,3186,Grove St PATH,3267,Morris Canal,33569,Annual Membership,Subscriber
95,239,2018-05-01 07:17:30,2018-05-01 07:21:29,3207,Oakland Ave,3640,Journal Square,26311,Annual Membership,Subscriber
100,710,2018-05-01 07:21:52,2018-05-01 07:33:43,3192,Liberty Light Rail,3183,Exchange Place,29271,Annual Membership from Citi Bike App,Subscriber

In [34]:
df

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,200,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32423,396,2018-05-30 13:49:18,2018-05-30 13:55:55,3184,Paulus Hook,3279,Dixon Mills,29639,Join Citi Bike for $14.95/month,Subscriber
32424,313,2018-05-30 13:49:21,2018-05-30 13:54:35,3202,Newport PATH,3639,Harborside,26301,$25 Off Annual Membership,Subscriber
32425,316,2018-05-30 13:49:51,2018-05-30 13:55:08,3220,5 Corners Library,3195,Sip Ave,29260,Annual Membership,Subscriber
32426,1130,2018-05-30 13:50:52,2018-05-30 14:09:42,3281,Leonard Gordon Park,3213,Van Vorst Park,26239,Annual Membership,Subscriber
32427,369,2018-05-30 13:50:58,2018-05-30 13:57:08,3220,5 Corners Library,3207,Oakland Ave,33660,Annual Membership,Subscriber

In [18]:
new_df = df.head(10)

e_list = []


for i in new_df.index:
    e_list.append(f"row_{i}")
    
new_df.index = e_list

new_df

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
row_1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
row_2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_3,200,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
row_4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
row_5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
row_6,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
row_7,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
row_8,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300,Annual Membership,Subscriber
row_9,170,2018-05-01 05:13:52,2018-05-01 05:16:43,3206,Hilltop,3195,Sip Ave,33555,$25 Off Annual Membership,Subscriber

In [20]:
new_df[4:8]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
row_5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
row_6,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
row_7,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber

In [22]:
new_df['row_4' : 'row_8']

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
row_5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
row_6,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
row_7,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
row_8,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300,Annual Membership,Subscriber

In [24]:
new_df[0:3]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
row_1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
row_2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber

In [26]:
new_df['row_0' : 'row_3']

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
row_1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
row_2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_3,200,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer

In [27]:
new_df['row_2':'row_8']

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_3,200,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
row_4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
row_5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
row_6,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
row_7,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
row_8,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300,Annual Membership,Subscriber

# Loc
- You can perform slicing on rows and columns
- Only userdefined indexing and slicing is allowed

[rows , columns]

In [32]:
new_df.loc['row_2' : 'row_5' , 'starttime' : 'bikeid']

,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid
row_2,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217
row_3,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662
row_4,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271
row_5,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298

In [33]:
new_df

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
row_1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
row_2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_3,200,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
row_4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
row_5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
row_6,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
row_7,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
row_8,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300,Annual Membership,Subscriber
row_9,170,2018-05-01 05:13:52,2018-05-01 05:16:43,3206,Hilltop,3195,Sip Ave,33555,$25 Off Annual Membership,Subscriber

In [36]:
# starttime , start station id , end station id , bikeid


# row_7 to row_2

new_df.loc['row_7':'row_2':-1 , 'starttime':'bikeid': 2 ]

                 starttime  start station id  end station id  bikeid
row_7  2018-05-01 05:11:50              3207            3185   33624
row_6  2018-05-01 05:05:46              3225            3186   33619
row_5  2018-05-01 04:37:05              3194            3195   29298
row_4  2018-05-01 04:27:12              3207            3195   15271
row_3  2018-05-01 02:03:29              3185            3186   29662
row_2  2018-05-01 01:31:29              3194            3193   29217

In [38]:
df.loc[5:10 , ::2]

,tripduration,stoptime,start station name,end station name,name_localizedValue
5,176,2018-05-01 04:40:01,McGinley Square,Sip Ave,Annual Membership
6,577,2018-05-01 05:15:23,Baldwin at Montgomery,Grove St PATH,Annual Membership from Citi Bike App
7,830,2018-05-01 05:25:41,Oakland Ave,City Hall,Annual Membership
8,395,2018-05-01 05:18:42,Baldwin at Montgomery,Grove St PATH,Annual Membership
9,170,2018-05-01 05:16:43,Hilltop,Sip Ave,$25 Off Annual Membership
10,353,2018-05-01 05:24:29,Baldwin at Montgomery,Sip Ave,Annual Membership

In [43]:
# 100 - 200 loc
df.loc[100:200  , 'starttime'::2]

               starttime  start station id  end station id  bikeid    usertype
100  2018-05-01 07:21:52              3192            3183   29271  Subscriber
101  2018-05-01 07:22:01              3281            3640   33555  Subscriber
102  2018-05-01 07:22:42              3269            3186   26316  Subscriber
103  2018-05-01 07:22:59              3277            3186   33628  Subscriber
104  2018-05-01 07:23:51              3681            3275   29245  Subscriber
..                   ...               ...             ...     ...         ...
196  2018-05-01 08:08:19              3277            3186   33572  Subscriber
197  2018-05-01 08:08:26              3199            3184   29293  Subscriber
198  2018-05-01 08:08:32              3267            3183   33640  Subscriber
199  2018-05-01 08:09:21              3194            3195   33652  Subscriber
200  2018-05-01 08:10:14              3209            3186   29127  Subscriber

[101 rows x 5 columns]

# iloc
- Slicing on columns and on rows is possible
- Only Zero indexing is allowed 

- Start --> inclusive
- Stop --> Exclusive

In [45]:
new_df.iloc['row_1' : 'row_5']

TypeError: cannot do positional indexing on Index with these indexers [row_1] of type str

In [48]:
new_df.iloc[2:7 , 1:8]

,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid
row_2,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217
row_3,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662
row_4,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271
row_5,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298
row_6,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619

# Filtering the data

In [52]:
df['usertype'] == 'Customer'

0        False
1         True
2        False
3         True
4        False
         ...
32423    False
32424    False
32425    False
32426    False
32427    False
Name: usertype, Length: 32428, dtype: bool

In [50]:
df.loc[df['usertype'] == 'Customer']

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
3,200,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
35,367,2018-05-01 06:28:03,2018-05-01 06:34:10,3278,Monmouth and 6th,3186,Grove St PATH,26235,Single Ride,Customer
139,699,2018-05-01 07:45:27,2018-05-01 07:57:07,3268,Lafayette Park,3214,Essex Light Rail,33562,Single Ride,Customer
151,334,2018-05-01 07:52:39,2018-05-01 07:58:14,3201,Dey St,3195,Sip Ave,26178,24 Hour,Customer
...,...,...,...,...,...,...,...,...,...,...
32348,842,2018-05-30 12:15:18,2018-05-30 12:29:21,3194,McGinley Square,3195,Sip Ave,29463,3-Day Pass from Citi Bike App,Customer
32352,278,2018-05-30 12:21:07,2018-05-30 12:25:46,3214,Essex Light Rail,3214,Essex Light Rail,33680,24 Hour,Customer
32353,1004,2018-05-30 12:21:20,2018-05-30 12:38:04,3214,Essex Light Rail,3183,Exchange Place,29646,24 Hour,Customer
32358,557,2018-05-30 12:28:48,2018-05-30 12:38:06,3214,Essex Light Rail,3183,Exchange Place,26198,24 Hour,Customer
32391,4387,2018-05-30 13:12:04,2018-05-30 14:25:12,3213,Van Vorst Park,3213,Van Vorst Park,26272,Single Ride,Customer

In [53]:
# Extract tripduration >= 1000

df.loc[df['tripduration'] >= 1000]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
32,2056,2018-05-01 06:25:13,2018-05-01 06:59:30,3185,City Hall,3185,City Hall,29219,Annual Membership,Subscriber
149,1020,2018-05-01 07:51:18,2018-05-01 08:08:19,3191,Union St,3195,Sip Ave,29593,Annual Membership,Subscriber
194,1384,2018-05-01 08:07:19,2018-05-01 08:30:24,3281,Leonard Gordon Park,3183,Exchange Place,29508,Join Citi Bike for $14.95/month,Subscriber
220,2198,2018-05-01 08:17:07,2018-05-01 08:53:46,3192,Liberty Light Rail,3183,Exchange Place,26257,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32388,1802,2018-05-30 13:09:34,2018-05-30 13:39:36,3202,Newport PATH,3202,Newport PATH,29679,Annual Membership,Subscriber
32391,4387,2018-05-30 13:12:04,2018-05-30 14:25:12,3213,Van Vorst Park,3213,Van Vorst Park,26272,Single Ride,Customer
32393,1152,2018-05-30 13:12:48,2018-05-30 13:32:00,3639,Harborside,3639,Harborside,26210,NYCHA Membership (Renewal),Subscriber
32397,1770,2018-05-30 13:17:41,2018-05-30 13:47:12,3196,Riverview Park,3192,Liberty Light Rail,33630,Annual Membership,Subscriber
32426,1130,2018-05-30 13:50:52,2018-05-30 14:09:42,3281,Leonard Gordon Park,3213,Van Vorst Park,26239,Annual Membership,Subscriber

In [54]:
# Extract tripduration >= 1000 and usertype == 'Customer'

df.loc[(df['tripduration'] >= 1000) & (df['usertype'] == 'Customer')]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
222,4929,2018-05-01 08:17:21,2018-05-01 09:39:31,3183,Exchange Place,3183,Exchange Place,29520,24 Hour,Customer
408,3191,2018-05-01 10:05:07,2018-05-01 10:58:19,3183,Exchange Place,3212,Christ Hospital,33593,24 Hour,Customer
466,1840,2018-05-01 11:53:20,2018-05-01 12:24:01,3213,Van Vorst Park,3213,Van Vorst Park,33615,24 Hour,Customer
467,1835,2018-05-01 11:53:36,2018-05-01 12:24:11,3213,Van Vorst Park,3213,Van Vorst Park,29483,24 Hour,Customer
...,...,...,...,...,...,...,...,...,...,...
32293,2230,2018-05-30 11:11:17,2018-05-30 11:48:28,3205,JC Medical Center,3205,JC Medical Center,26194,3 Day,Customer
32295,1896,2018-05-30 11:12:13,2018-05-30 11:43:50,3192,Liberty Light Rail,3202,Newport PATH,33670,24 Hour,Customer
32327,1135,2018-05-30 11:54:15,2018-05-30 12:13:11,3201,Dey St,3483,Montgomery St,33604,Single Ride,Customer
32353,1004,2018-05-30 12:21:20,2018-05-30 12:38:04,3214,Essex Light Rail,3183,Exchange Place,29646,24 Hour,Customer
32391,4387,2018-05-30 13:12:04,2018-05-30 14:25:12,3213,Van Vorst Park,3213,Van Vorst Park,26272,Single Ride,Customer

In [56]:
df.loc[(df['name_localizedValue']=='Annual Membership') | (df['name_localizedValue']=='24 Hour')]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
3,200,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32421,255,2018-05-30 13:45:38,2018-05-30 13:49:54,3183,Exchange Place,3213,Van Vorst Park,29443,Annual Membership,Subscriber
32422,108,2018-05-30 13:49:12,2018-05-30 13:51:00,3202,Newport PATH,3199,Newport Pkwy,29461,Annual Membership,Subscriber
32425,316,2018-05-30 13:49:51,2018-05-30 13:55:08,3220,5 Corners Library,3195,Sip Ave,29260,Annual Membership,Subscriber
32426,1130,2018-05-30 13:50:52,2018-05-30 14:09:42,3281,Leonard Gordon Park,3213,Van Vorst Park,26239,Annual Membership,Subscriber
32427,369,2018-05-30 13:50:58,2018-05-30 13:57:08,3220,5 Corners Library,3207,Oakland Ave,33660,Annual Membership,Subscriber

# Changing the name of the column

In [62]:
new_df.rename(columns= {'tripduration' : 'Duration' } , inplace = True)

C:\Users\Mohammed Israr\AppData\Local\Temp\ipykernel_2052\941567250.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.rename(columns= {'tripduration' : 'Duration'} , inplace = True)

In [67]:
new_df.drop(columns= ['starttime' , 'stoptime'] , inplace = True)

C:\Users\Mohammed Israr\AppData\Local\Temp\ipykernel_2052\3400865687.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.drop(columns= ['starttime' , 'stoptime'] , inplace = True)

In [68]:
new_df

,Duration,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_0,338,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
row_1,1482,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
row_2,232,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_3,200,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
row_4,303,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
row_5,176,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
row_6,577,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
row_7,830,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
row_8,395,3225,Baldwin at Montgomery,3186,Grove St PATH,26300,Annual Membership,Subscriber
row_9,170,3206,Hilltop,3195,Sip Ave,33555,$25 Off Annual Membership,Subscriber

# Adding Columns and deleting columns

In [69]:
df = pd.read_csv('datasets/international_org.csv')
df

  Organization Name  Headquater
0               FAO        Rome
1               ICJ   The Hague
2               IMF  Washington
3            UNESCO       Paris
4               UNO    New York
5        World Bank  Washington

In [70]:
df['new_col_1'] = 1995

In [72]:
df['new_col_2'] = [1995 , 2000,405,67,45,34]

In [75]:
df['new_col_3'] = range(100,106)

In [76]:
df

  Organization Name  Headquater  new_col_1  new_col_2  new_col_3
0               FAO        Rome       1995       1995        100
1               ICJ   The Hague       1995       2000        101
2               IMF  Washington       1995        405        102
3            UNESCO       Paris       1995         67        103
4               UNO    New York       1995         45        104
5        World Bank  Washington       1995         34        105

# apply

In [ ]:
def funct(x):
    return x/5

In [77]:
df['new_col_4'] = df['new_col_3'].apply(lambda x : x/5)

In [78]:
df

  Organization Name  Headquater  new_col_1  new_col_2  new_col_3  new_col_4
0               FAO        Rome       1995       1995        100       20.0
1               ICJ   The Hague       1995       2000        101       20.2
2               IMF  Washington       1995        405        102       20.4
3            UNESCO       Paris       1995         67        103       20.6
4               UNO    New York       1995         45        104       20.8
5        World Bank  Washington       1995         34        105       21.0

In [79]:
df['new_col_5'] = df['Organization Name'].apply(lambda x: x[0])

In [81]:
df['new_col_6'] = df['new_col_3'].apply(lambda x : 'Even' if x%2==0 else 'Odd')

In [82]:
df

,Organization Name,Headquater,new_col_1,new_col_2,new_col_3,new_col_4,new_col_5,new_col_6
0,FAO,Rome,1995,1995,100,20.0,F,Even
1,ICJ,The Hague,1995,2000,101,20.2,I,Odd
2,IMF,Washington,1995,405,102,20.4,I,Even
3,UNESCO,Paris,1995,67,103,20.6,U,Odd
4,UNO,New York,1995,45,104,20.8,U,Even
5,World Bank,Washington,1995,34,105,21.0,W,Odd

# Assign

In [85]:
df = df.assign(col_7 = lambda x: x.new_col_3 * x.new_col_4)

In [86]:
df

,Organization Name,Headquater,new_col_1,new_col_2,new_col_3,new_col_4,new_col_5,new_col_6,col_7
0,FAO,Rome,1995,1995,100,20.0,F,Even,2000.0
1,ICJ,The Hague,1995,2000,101,20.2,I,Odd,2040.2
2,IMF,Washington,1995,405,102,20.4,I,Even,2080.8
3,UNESCO,Paris,1995,67,103,20.6,U,Odd,2121.8
4,UNO,New York,1995,45,104,20.8,U,Even,2163.2
5,World Bank,Washington,1995,34,105,21.0,W,Odd,2205.0

In [87]:
df['new_col_8']  = list(map((lambda x,y: x if x>y else y) , df['new_col_2'] , df['new_col_3']))

In [88]:
df

,Organization Name,Headquater,new_col_1,new_col_2,new_col_3,new_col_4,new_col_5,new_col_6,col_7,new_col_8
0,FAO,Rome,1995,1995,100,20.0,F,Even,2000.0,1995
1,ICJ,The Hague,1995,2000,101,20.2,I,Odd,2040.2,2000
2,IMF,Washington,1995,405,102,20.4,I,Even,2080.8,405
3,UNESCO,Paris,1995,67,103,20.6,U,Odd,2121.8,103
4,UNO,New York,1995,45,104,20.8,U,Even,2163.2,104
5,World Bank,Washington,1995,34,105,21.0,W,Odd,2205.0,105

# Deleting columns

### Del

In [90]:
del df['new_col_8']

In [92]:
del [df['col_7'] , df['new_col_6']]

In [93]:
df

,Organization Name,Headquater,new_col_1,new_col_2,new_col_3,new_col_4,new_col_5
0,FAO,Rome,1995,1995,100,20.0,F
1,ICJ,The Hague,1995,2000,101,20.2,I
2,IMF,Washington,1995,405,102,20.4,I
3,UNESCO,Paris,1995,67,103,20.6,U
4,UNO,New York,1995,45,104,20.8,U
5,World Bank,Washington,1995,34,105,21.0,W

# Drop

In [96]:
df.drop(columns= 'new_col_5' , inplace = True)

In [99]:
df.drop(columns= ['new_col_4' , 'new_col_1'] , inplace = True)

In [101]:
df.drop(['new_col_3' , 'new_col_2'] , axis = 1 , inplace = True)

In [102]:
df

  Organization Name  Headquater
0               FAO        Rome
1               ICJ   The Hague
2               IMF  Washington
3            UNESCO       Paris
4               UNO    New York
5        World Bank  Washington

# Adding and deleting rows